In [278]:
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
import time
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException, ElementNotVisibleException, TimeoutException
import re
from selenium.webdriver.chrome.options import Options

# 1.Scrape the details of most viewed videos on YouTube from Wikipedia.

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [46]:
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-46-d478c62c7cb5>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [47]:
num = []
vid = []
uplodr = []
views = []
date = []

In [48]:
for i in range(1,31):
    num_tag = driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
    try:
        num.append(num_tag.text)
    except:
        num.append('-')
        
for i in range(1,31):
    vid_tag = driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
    try:
        vid.append(vid_tag.text.strip().split('"')[1])
        #vid.append(vid_tag.text)
    except:
        vid.append('-')
        
for i in range(1,31):
    uplod_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
    try:
        uplodr.append(uplod_tag.text)
    except:
        uplodr.append('-')

for i in range(1,31):
    view_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
    try:
        views.append(view_tag.text)
    except:
        views.append('-')
        
for i in range(1,31):
    date_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")
    try:
        date.append(date_tag.text)
    except:
        date.append(date_tag.text)
    
    

    
topratedvideo = {"Rank":num,"Name":vid,"Artist":uplodr,"Upload Date":date,"Views":views}
topratedvideoDF = pd.DataFrame(topratedvideo)
topratedvideoDF.reset_index(drop = True, inplace = True)
topratedvideoDF.index+=1

<ipython-input-48-995a804eecbf>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  num_tag = driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
<ipython-input-48-995a804eecbf>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  vid_tag = driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
<ipython-input-48-995a804eecbf>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  uplod_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
<ipython-input-48-995a804eecbf>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  view_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
<ipython-input-48-995a804eecbf>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  date_tag = driver.find_element_by_xpath(f"//*[@id = 'mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")

In [49]:
topratedvideoDF

,Rank,Name,Artist,Upload Date,Views
1,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.96
2,2.,Despacito,Luis Fonsi,"January 12, 2017",7.69
3,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.08
4,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.58
5,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.38
6,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.83
7,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.55
8,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.48
9,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.42
10,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.39
11,11.,Gangnam Style,Psy,"July 15, 2012",4.30
12,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.79
13,13.,Sugar,Maroon 5,"January 14, 2015",3.62
14,14.,Sorry,Justin Bieber,"October 22, 2015",3.50
15,15.,Roar,Katy Perry,"September 5, 2013",3.50
16,16.,Counting Stars,OneRepublic,"May 31, 2013",3.48
17,17.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.47
18,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.39
19,19.,Girls Like You,Maroon 5,"May 31, 2018",3.21
20,20.,Faded,Alan Walker,"December 3, 2015",3.21
21,21.,Dark Horse,Katy Perry,"February 20, 2014",3.20
22,22.,Axel F,Crazy Frog,"June 16, 2009",3.16
23,23.,Let Her Go,Passenger,"July 25, 2012",3.15
24,24.,Bailando,Enrique Iglesias,"April 11, 2014",3.15
25,25.,Lean On,Major Lazer,"March 22, 2015",3.15
26,26.,Shake It Off,Taylor Swift,"August 18, 2014",3.13
27,27.,Perfect,Ed Sheeran,"November 9, 2017",3.06
28,28.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.05
29,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.02
30,30.,Mi Gente,J Balvin,"June 29, 2017",3.02

# 2.Scrape the details team India’s international fixtures from bcci.tv.

Url = https://www.bcci.tv/.

You need to find following details: A) Match title (I.e. 1st ODI) (B) Series (C) Place (D) Date (E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [201]:
url = "https://www.bcci.tv/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-201-5aa65353f330>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [202]:
btn=driver.find_element_by_xpath("//li[@class = 'nav-item ml-0']")
# driver.get(btn.get_attribute("href"))
btn.click()

<ipython-input-202-f5d3f135f38e>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  btn=driver.find_element_by_xpath("//li[@class = 'nav-item ml-0']")

In [203]:
title = []
series =[]
place = []
date = []
time = []

In [204]:
for i in driver.find_elements_by_xpath("//div[@class = 'fix-place ng-binding ng-scope']"):
    title.append(i.text.strip().split('-')[0])
    
for i in driver.find_elements_by_xpath("//div[@class = 'fix-place ng-binding ng-scope']"):
    place.append(i.text.strip().split('-')[1])
    
for i in driver.find_elements_by_xpath("//div[@class = 'match-card-left match-schedule']/h5[1]"):
    date.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class = 'match-card-right match-schedule ']/h5[1]"):
    time.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class = 'fixture-card-top']/h5[2]/span"):
    series.append(i.text)
    
    
match = {"Title":title,"Series":series,"PLace":place,"Date":date,"Time":time}
matchDF = pd.DataFrame(match)
matchDF.reset_index(drop = True, inplace = True)
matchDF.index+=1

<ipython-input-204-4b230602b3db>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class = 'fix-place ng-binding ng-scope']"):
<ipython-input-204-4b230602b3db>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class = 'fix-place ng-binding ng-scope']"):
<ipython-input-204-4b230602b3db>:7: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class = 'match-card-left match-schedule']/h5[1]"):
<ipython-input-204-4b230602b3db>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class = 'match-card-right match-schedule ']/h5[1]"):
<ipython-input-204-4b230602b3db>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class = 'fixture-card-top']/h5[2]/span"):

In [205]:
matchDF

,Title,Series,PLace,Date,Time
1,3rd Test,INDIA TOUR OF SOUTH AFRICA TEST SERIES 2021-22,"Newlands, Cape Town",11 JAN 2022,2:00 PM IST
2,1st ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl",19 JAN 2022,2:00 PM IST
3,2nd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl",21 JAN 2022,2:00 PM IST
4,3rd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Newlands, Cape Town",23 JAN 2022,2:00 PM IST
5,1st ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"NARENDRA MODI STADIUM, Ahmedabad",6 FEB 2022,9:30 AM IST
6,2nd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Sawai Mansingh Stadium, Jaipur",9 FEB 2022,9:30 AM IST
7,3rd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Eden Gardens, Kolkata",12 FEB 2022,9:30 AM IST
8,1st T20I,WEST INDIES TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium, Cuttack",15 FEB 2022,7:30 PM IST

# 3. Scrape the details of selenium exception from guru99.com.

Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [227]:
url = "https://www.guru99.com/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

#opening Selenium link
selbtn = driver.find_element_by_xpath("//div[@class = 'featured-box cloumnsize1']/ul[1]/li[3]/a")
selbtn.click()

#opening Tutor link
tutbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
tutbtn.click()

#Assigning empty list
name = []
desc = []

#Scrapping data from weblink

for i in range (2,43):
    name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
    try:
        name.append(name_tag.text)
    except:
        name.append('-')

for i in range (2,43):
    desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")
    try:
        desc.append(desc_tag.text)
    except:
        desc.append('-')
        
#Creating DataFrame
excep = {"Name":name,"Description":desc}
Selenium_ExceptionDF = pd.DataFrame(excep)
Selenium_ExceptionDF.reset_index(drop = True, inplace = True)
Selenium_ExceptionDF.index+=1

#opening DataFrame

Selenium_ExceptionDF

<ipython-input-227-5eba58f44f3a>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
<ipython-input-227-5eba58f44f3a>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selbtn = driver.find_element_by_xpath("//div[@class = 'featured-box cloumnsize1']/ul[1]/li[3]/a")
<ipython-input-227-5eba58f44f3a>:11: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  tutbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
<ipython-input-227-5eba58f44f3a>:21: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
<ipython-input-227-5eba58f44f3a>:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")

,Name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP

D) GSDP

E) Share

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [284]:
url = "http://statisticstimes.com/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-284-1662c9321b11>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [288]:
# clicking on Economy Dropdown Button

eco_btn = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
try:
    eco_btn.click()
except:
    pass

#selection India from dropdown list

ind = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")
try:
    ind.click()
except:
    pass
time.sleep(10)

# Disable the chrome ads
option1 = Options()
option1.add_argument("--disable-noifications")

<ipython-input-288-5664e6433828>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  eco_btn = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
<ipython-input-288-5664e6433828>:11: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ind = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")

In [289]:
# Selecting GDP of Indian State

indstate = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
try:
    indstate.click()
except:
    pass

<ipython-input-289-b0faf2a58608>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  indstate = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

In [290]:
# Creating empty list

rank = []
name = []
gsdp19_20 = []
gsdp18_19 = []
share = []
dgp = []

In [291]:
for i in range (1,34):
    rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
    try:
        rank.append(rank_tag.text)
    except:
        rank.append('-')
        
for i in range(1,34):
    name_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
    try:
        name.append(name_tag.text)
    except:
        name.append('-')
        
for i in range(1,34):
    gsdp19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
    try:
        gsdp19_20.append(gsdp19_tag.text)
    except:
        gsdp19_20.append(gsdp19_tag.text)
        
for i in range(1,34):
    gsdp18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
    try:
        gsdp18_19.append(gsdp18_tag.text)
    except:
        gsdp18_19.append('-')
        
for i in range(1,34):
    share_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
    try:
        share.append(share_tag.text)
    except:
        share.append('-')

for i in range(1,34):
    gdp_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")
    try:
        dgp.append(gdp_tag.text)
    except:
        dgp.append('-')

<ipython-input-291-361c8cea1fd9>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
<ipython-input-291-361c8cea1fd9>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  name_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
<ipython-input-291-361c8cea1fd9>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gsdp19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
<ipython-input-291-361c8cea1fd9>:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gsdp18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
<ipython-input-291-361c8cea1fd9>:30: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  share_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
<ipython-input-291-361c8cea1fd9>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")

In [292]:
IGDP = {"Rank":rank,"State":name,"GSDP 19-20":gsdp19_20,"GSDP 18-19":gsdp18_19,"Share":share,"GDP in $billion":dgp}
IndiaGDPDF = pd.DataFrame(IGDP)
IndiaGDPDF.reset_index(drop = True, inplace = True)
IndiaGDPDF.index+=1

In [293]:
IndiaGDPDF

,Rank,State,GSDP 19-20,GSDP 18-19,Share,GDP in $billion
1,1,Maharashtra,-,"2,632,792",13.94%,399.921
2,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
3,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
4,4,Gujarat,-,"1,502,899",7.96%,228.290
5,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
6,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
7,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
8,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
9,9,Telangana,"969,604","861,031",4.56%,130.791
10,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
11,11,Kerala,-,"781,653",4.14%,118.733
12,12,Delhi,"856,112","774,870",4.10%,117.703
13,13,Haryana,"831,610","734,163",3.89%,111.519
14,14,Bihar,"611,804","530,363",2.81%,80.562
15,15,Punjab,"574,760","526,376",2.79%,79.957
16,16,Odisha,"521,275","487,805",2.58%,74.098
17,17,Assam,-,"315,881",1.67%,47.982
18,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
19,19,Jharkhand,"328,598","297,204",1.57%,45.145
20,20,Uttarakhand,-,"245,895",1.30%,37.351
21,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
22,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
23,23,Goa,"80,449","73,170",0.39%,11.115
24,24,Tripura,"55,984","49,845",0.26%,7.571
25,25,Chandigarh,-,"42,114",0.22%,6.397
26,26,Puducherry,"38,253","34,433",0.18%,5.230
27,27,Meghalaya,"36,572","33,481",0.18%,5.086
28,28,Sikkim,"32,496","28,723",0.15%,4.363
29,29,Manipur,"31,790","27,870",0.15%,4.233
30,30,Nagaland,-,"27,283",0.14%,4.144
31,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
32,32,Mizoram,"26,503","22,287",0.12%,3.385
33,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.

Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [364]:
url = "https://github.com/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-364-9de69daa1c0e>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [365]:
exp_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
try:
    exp_btn.click()
except:
    pass

<ipython-input-365-9ca34e03a759>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  exp_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")

In [366]:
trnd_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trnd_url.get_attribute("href")
driver.get(urls)

<ipython-input-366-d39fe1f317e6>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trnd_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")

In [367]:
# Creating Empty list

repo_urls = []
rep_title = []
description = []
contributors = []
language = []
lang = []

In [368]:
# Fetching URLs for each repository

repo = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']//a")
for i in repo:
    repo_urls.append(i.get_attribute("href"))
    
#Scrapping data of Repository Title

title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    rep_title.append(i.text)
    
#Scrapping data from every Repository page:
for i in repo_urls:
    driver.get(i)
    time.sleep(3)

    #Scrapping data of description:
    try:
        desc = driver.find_element_by_xpath("//p[@class = 'f4 my-3']")
        description.append(desc.text)
    except:
        description.append('-')
        
    #SCrapping data of Contributors:
    try:
        cont = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")
        contributors.append(cont.text)
    except:
        contributors.append('-')
    
    #Scrapping language used:
    try:
        for i in driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]"):
            lang.append(i.text)
        language.append(lang)
    except:
        language.append('-')

<ipython-input-368-c0a6990d2cb0>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  repo = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']//a")
<ipython-input-368-c0a6990d2cb0>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
<ipython-input-368-c0a6990d2cb0>:20: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc = driver.find_element_by_xpath("//p[@class = 'f4 my-3']")
<ipython-input-368-c0a6990d2cb0>:27: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  cont = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")
<ipython-input-368-c0a6990d2cb0>:34: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  for i in driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]"):

In [369]:
gith = {"Repository Title":rep_title,"Repository Description":description,"Contributors Counts":contributors,"Language Used":language}
GitHubDF = pd.DataFrame(gith)
GitHubDF.reset_index(drop = True, inplace = True)
GitHubDF.index+=1

In [370]:
GitHubDF

,Repository Title,Repository Description,Contributors Counts,Language Used
1,Marak / faker.js,What really happened with Aaron Swartz?,-,-
2,ReactiveX / RxSwift,Reactive Programming in Swift,321,-
3,LingDong- / shan-shui-inf,Procedurally generated Chinese landscape paint...,2,-
4,tensorflow / tensorflow,An Open Source Machine Learning Framework for ...,"3,048",-
5,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,373",-
6,Igglybuff / awesome-piracy,A curated list of awesome warez and piracy links,118,-
7,LaravelDaily / laravel-tips,Awesome tips for Laravel,36,-
8,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,18,-
9,withshepherd / faker.js,-,200,-
10,MichaelCade / 90DaysOfDevOps,This repository is my documenting repository f...,5,-
11,ascoders / weekly,前端精读周刊。帮你理解最前沿、实用的技术。,58,-
12,microsoft / PowerToys,Windows system utilities to maximize productivity,262,-
13,wmjordan / PDFPatcher,PDF补丁丁,3,-
14,DioxusLabs / dioxus,Elegant React-like library for building user i...,6,-
15,commit-live-students / Data_Science_Masters_Pr...,-,-,-
16,facebook / folly,An open-source C++ library developed and used ...,622,-
17,josephmisiti / awesome-machine-learning,A curated list of awesome Machine Learning fra...,522,-
18,appwrite / appwrite,Appwrite is a secure end-to-end backend server...,226,-
19,golang / go,The Go programming language,"1,769",-
20,TheAlgorithms / Python,All Algorithms implemented in Python,792,-
21,M3-org / awesome-metaverse,Awesome metaverse projects,8,-
22,kdn251 / interviews,Everything you need to know to get the job.,30,-
23,hashicorp / terraform-provider-aws,Terraform AWS provider,"2,096",-
24,up9inc / mizu,API traffic viewer for Kubernetes enabling you...,13,-
25,quarkusio / quarkus,Quarkus: Supersonic Subatomic Java.,580,-

# 6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [80]:
url = "https://www.billboard.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
time.sleep(3)
# driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

<ipython-input-80-eac9c21c8820>:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [83]:
hot_100 = driver.find_element_by_xpath("//*[@id='main-wrapper']/header/div[2]/div/nav/ul/li[1]/a").click()
time.sleep(2)

Song_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")]

Artist_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")]

Last_week_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")]

Peak_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")]

Weeks_on_board=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")]

# Creating data frame
Songs=pd.DataFrame({"SONG NAME":Song_name, "ARTIST":Artist_name, "LAST WEEK RANK":Last_week_rank,
                    "PEAK RANK":Peak_rank, "WEEK ON BORD":Weeks_on_board})

<ipython-input-83-54bf0895a738>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  hot_100 = driver.find_element_by_xpath("//*[@id='main-wrapper']/header/div[2]/div/nav/ul/li[1]/a").click()
<ipython-input-83-54bf0895a738>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Song_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")]
<ipython-input-83-54bf0895a738>:6: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Artist_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")]
<ipython-input-83-54bf0895a738>:8: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Last_week_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")]
<ipython-input-83-54bf0895a738>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Peak_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")]
<ipython-input-83-54bf0895a738>:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Weeks_on_board=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")]

Empty DataFrame
Columns: [SONG NAME, ARTIST, LAST WEEK RANK, PEAK RANK, WEEK ON BORD]
Index: []

In [85]:
Songs

Empty DataFrame
Columns: [SONG NAME, ARTIST, LAST WEEK RANK, PEAK RANK, WEEK ON BORD]
Index: []

# 7. Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [172]:
url = "https://www.naukri.com/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-172-8209a3c365e5>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [173]:
search_field = driver.find_element_by_xpath("//input[@class = 'suggestor-input ']")
search_field.send_keys("recruiters")

search_bt = driver.find_element_by_xpath("//div[@class='qsbSubmit']").click()

<ipython-input-173-2a584871ca7e>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_field = driver.find_element_by_xpath("//input[@class = 'suggestor-input ']")
<ipython-input-173-2a584871ca7e>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_bt = driver.find_element_by_xpath("//div[@class='qsbSubmit']").click()

In [174]:
recruit_btn=driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div') #recruiters button

try:
    recruit_btn.click()#click recruiters button
except ElementNotInteractableException:
    pass
driver.switch_to.window(driver.window_handles[1])#switch to recruiters tab

<ipython-input-174-bd8931a15540>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  recruit_btn=driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div') #recruiters button

In [175]:
searchjob = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
searchjob.send_keys("Data Science")

serchbttn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()

<ipython-input-175-6c5e8fca75de>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searchjob = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
<ipython-input-175-6c5e8fca75de>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  serchbttn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()

In [176]:
# Creating Empty List

Name = []
Designation = []
Company = []
Skillshire = []
location = []

In [177]:
name_tag = driver.find_elements_by_xpath("//a[@class = 'ellipsis']/span")[:50]
for i in name_tag:
    try:
        Name.append(i.text)
    except:
        Name.append('-')
        
desg_tag = driver.find_elements_by_xpath("//span[@class = 'ellipsis clr']")[:50]
for d in desg_tag:
    try:
        Designation.append(d.text)
    except:
        Designation.append('-')
        
comp_tag = driver.find_elements_by_xpath("//p[@class = 'highlightable']/a[2]")[:50]
for c in comp_tag:
    try:
        Company.append(c.text)
    except:
        Company.append('-')
        
skill_tag = driver.find_elements_by_xpath("//div[@class = 'hireSec highlightable']")[:50]
for s in skill_tag:
    try:
        Skillshire.append(s.text)
    except:
        Skillshire.append('-')

<ipython-input-177-69ffbe89b6ce>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tag = driver.find_elements_by_xpath("//a[@class = 'ellipsis']/span")[:50]
<ipython-input-177-69ffbe89b6ce>:8: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desg_tag = driver.find_elements_by_xpath("//span[@class = 'ellipsis clr']")[:50]
<ipython-input-177-69ffbe89b6ce>:15: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  comp_tag = driver.find_elements_by_xpath("//p[@class = 'highlightable']/a[2]")[:50]
<ipython-input-177-69ffbe89b6ce>:22: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  skill_tag = driver.find_elements_by_xpath("//div[@class = 'hireSec highlightable']")[:50]

In [178]:
nameurl = []

In [179]:
nametag = driver.find_elements_by_xpath("//p[@class = 'highlightable']/a[1]")

<ipython-input-179-3bfe303e24ee>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nametag = driver.find_elements_by_xpath("//p[@class = 'highlightable']/a[1]")

In [180]:
for r in nametag:
    try:
        nameurl.append(r.get_attribute("href"))
    except:
        nameurl.append("-")

In [183]:
for i in nameurl:
    driver.get(i)
    time.sleep(4)
    try:
        locationtag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
        location.append(locationtag.text)
    except NoSuchElementException:
        location.append('-')

<ipython-input-183-4c4e797458a5>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  locationtag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")

In [186]:
job = {"Name":Name,"Designation":Designation,"Company":Company,"Skills they hire for":Skillshire,"Location":location}
JobsDF = pd.DataFrame(job)
JobsDF.reset_index(drop = True, inplace = True)
JobsDF.index+=1

In [187]:
JobsDF

,Name,Designation,Company,Skills they hire for,Location
1,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
2,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
3,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
4,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
20,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
21,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
22,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
23,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
24,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
31,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
33,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
34,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
50,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore

# 8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [204]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-204-d12c58c01f83>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [205]:
name = []
author_name = []
volumes = []
publisher = []
genre = []

In [206]:
for i in range (1,101):
    try:
        book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
        name.append(book_tag.text)
    except:
        name.append('-')
        
for i in range(1,101):
    try:
        author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
        author_name.append(author_tag.text)
    except:
        author_name.append('-')
        
for i in range(1,101):
    try:
        vol_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
        volumes.append(vol_tag.text)
    except:
        volumes.append('-')
        
for i in range(1,101):
    try:
        pub_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
        publisher.append(pub_tag.text)
    except:
        publisher.append('-')
        
for i in range(1,101):
    try:
        gen_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")
        genre.append(gen_tag.text)
    except:
        genre.append('-')

<ipython-input-206-8862a7830b49>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
<ipython-input-206-8862a7830b49>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
<ipython-input-206-8862a7830b49>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  vol_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
<ipython-input-206-8862a7830b49>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  pub_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
<ipython-input-206-8862a7830b49>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gen_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")

In [207]:
book = {"Book Name":name,"Author Name":author_name,"Volumes Sold":volumes,"Publisher":publisher,"Genre":genre}
BookDF = pd.DataFrame(book)
BookDF.reset_index(drop = True, inplace = True)
BookDF.index+=1

In [208]:
BookDF

,Book Name,Author Name,Volumes Sold,Publisher,Genre
1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [267]:
url = "https://www.imdb.com/list/ls095964455/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-267-a82134a398b4>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [268]:
Name = []
Year = []
Genre = []
Runtime = []
Ratings = []
Votes = []

In [269]:
for i in range(1,101):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,101):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")
        
for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

for i in range(1,101):
    try:
        Runtime_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]")
        Runtime.append(Runtime_tag.text)
    except NoSuchElementException:
        Runtime.append("-")

for i in range(1,101):
    try:
        Ratings_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]")
        Ratings.append(Ratings_tag.text)
    except NoSuchElementException:
        Ratings.append("-")
for i in range(1,101):
    try:
        Votes_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[4]/span[2]")
        Votes.append(Votes_tag.text)
    except NoSuchElementException:
        Votes.append("-")

<ipython-input-269-45e274ec1bca>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a")
<ipython-input-269-45e274ec1bca>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Year_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]")
<ipython-input-269-45e274ec1bca>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Genre_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]")
<ipython-input-269-45e274ec1bca>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Runtime_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]")
<ipython-input-269-45e274ec1bca>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Ratings_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]")
<ipython-input-269-45e274ec1bca>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Votes_tag = driver.find_element_by_xpath(f"/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[4]/span[2]")

In [270]:
Top100shows = {'Name': Name,'Year span':Year,'Genre':Genre,'Run time':Runtime,'Ratings':Ratings,'Votes':Votes}

Top100showssDF = pd.DataFrame(Top100shows)

Top100showssDF

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,930,675"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"951,537"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"922,217"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"276,327"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"236,576"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,179"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,975"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"183,050"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,334"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"218,024"

# 10. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code

In [287]:
url = "https://archive.ics.uci.edu/"
driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

<ipython-input-287-d21123077e62>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/siddh/Downloads/chromedriver_win32/chromedriver.exe")

In [288]:
datasetbtn = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td/span/b/a").click()

<ipython-input-288-24c1bc3ec907>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  datasetbtn = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td/span/b/a").click()

In [289]:
name = []
datatype = []
task = []
attributetype = []
instance = []
attributeno = []
year = []

In [290]:
for i in range (1,622):
    try:
        name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
        name.append(name_tag.text)
    except:
        name.append('-')
        
for i in range(1,622):
    try:
        datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
        datatype.append(datatype_tag.text)
    except:
        datatype.append('-')
        
for i in range(1,622):
    try:
        task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
        task.append(task_tag.text)
    except:
        task.append('-')
        
for i in range(1,622):
    try:
        attrtype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
        attributetype.append(attrtype_tag.text)
    except:
        attributetype.append('-')
        
for i in range(1,622):
    try:
        instance_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
        instance.append(instance_tag.text)           
    except:
        instance.append('-')
        
for i in range(1,622):
    try:
        attributeno_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
        attributeno.append(attributeno_tag.text)
    except:
        attributeno.append('-')
        
for i in range(1,622):
    try:
        year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
        year.append(year_tag.text)
    except:
        year.append('-')

<ipython-input-290-ccdfa0418790>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
<ipython-input-290-ccdfa0418790>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
<ipython-input-290-ccdfa0418790>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
<ipython-input-290-ccdfa0418790>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  attrtype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
<ipython-input-290-ccdfa0418790>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  instance_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
<ipython-input-290-ccdfa0418790>:38: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  attributeno_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
<ipython-input-290-ccdfa0418790>:45: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")

In [291]:
repositories = {"Dataset Name":name,"Data Type":datatype,"Task":task,"Attribute Type":attributetype,"No of Instance":instance,"No of Attribute":attributeno,"Year":year}
RepositoriesDF = pd.DataFrame(repositories)
RepositoriesDF.drop(index = 0,inplace = True)

In [292]:
RepositoriesDF

,Dataset Name,Data Type,Task,Attribute Type,No of Instance,No of Attribute,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
616,REJAFADA,Multivariate,Classification,Integer,1996,6826,2020
617,Steel Industry Energy Consumption Dataset,Multivariate,Regression,Integer,35040,11,2020
618,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
620,Maternal Health Risk Data Set,,Classification,,1014,7,2020